api_platform:
    title: 'projectfilrougeBack'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    eager_loading:
        max_joins: 100
        fetch_partial: true
        force_eager: false
    collection:
        pagination:
            items_per_page: 5
    formats:
        jsonld:
            mime_types: [ 'application/ld+json' ]

        json:
            mime_types: [ 'application/json' ]

        html:
            mime_types: [ 'text/html' ]

        multipart:
            mime_types: ['multipart/form-data']